;; Order a List (Insertion Sort)
; (insertion_sort '(4 1 8 5 3))
; -> (1 3 4 5 8)
(defun insert (num list)
  (if (equal list ())
    (cons num list)
    (if (<= num (car list))
      (cons num list)
      (cons (car list) (insert num (cdr list))))))

(defun insertion_sort (lst)
  (if (null lst)
    ()
    (insert (car lst) (insertion_sort (cdr lst)))
  )
)
